
services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: deathnotedb
    volumes:
      - ./postgres:/var/lib/postgresql/data
  
  deathnoteapp:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    image: deathnote-docker
    container_name: deathnote
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - "${PORT}:${PORT}"
